services:
  backend:
    build: ./backend
    container_name: dramm_backend
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports: 
      # - "127.0.0.1:3001:3001"
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy


    
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      VITE_FIREBASE_KEY: ${VITE_FIREBASE_KEY}
      VITE_FIREBASE_DOMAIN: ${VITE_FIREBASE_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_SENDER_ID: ${VITE_FIREBASE_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_YELP_API_KEY: ${VITE_YELP_API_KEY}
      VITE_WEATHER_API_KEY: ${VITE_WEATHER_API_KEY}
      VITE_API_URL: ${VITE_API_URL}
      PORT: 8000
    args:
      VITE_FIREBASE_KEY: ${VITE_FIREBASE_KEY}
      VITE_FIREBASE_DOMAIN: ${VITE_FIREBASE_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_SENDER_ID: ${VITE_FIREBASE_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_YELP_API_KEY: ${VITE_YELP_API_KEY}
      VITE_WEATHER_API_KEY: ${VITE_WEATHER_API_KEY}
      VITE_API_URL: "localhost:3001"
    stdin_open: true
    ports: 
      # - "127.0.0.1:5173:5173"
      - "8000:80"
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: dramm
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:

    image: redis/redis-stack-server:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server
    #["redis-stack-server", "/etc/redis/redis.conf"] 
    #redis-stack-server --requirepass sOmE_sEcUrE_pAsS
    volumes: 
      - cache:/data
    
  # nginx:
  #   image: nginx:1.16.0-alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #      - backend
  #      - frontend

volumes:
  mongo-data:
    driver: local
  cache:
    driver: local
