version: '3.8'
services:
  backend:
    build: ./backend
    container_name: dramm_backend
    secrets:
      - VITE_FIREBASE_KEY
      - VITE_FIREBASE_DOMAIN
      - VITE_FIREBASE_PROJECT_ID
      - VITE_FIREBASE_STORAGE_BUCKET
      - VITE_FIREBASE_SENDER_ID
      - VITE_FIREBASE_APP_ID
      - VITE_YELP_API_KEY
      - VITE_WEATHER_API_KEY
    ports: 
      - "127.0.0.1:3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

    
  frontend:
    build: ./
    container_name: frontend
    
    ports: 
      - "127.0.0.1:5173:5173"
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules

secrets:
  VITE_FIREBASE_KEY:
    file: ./secret_VITE_FIREBASE_KEY.txt
  VITE_FIREBASE_DOMAIN:
    file: ./secret_VITE_FIREBASE_DOMAIN.txt
  VITE_FIREBASE_PROJECT_ID:
    file: ./secret_VITE_FIREBASE_PROJECT_ID.txt
  VITE_FIREBASE_STORAGE_BUCKET:
    file: ./secret_VITE_FIREBASE_STORAGE_BUCKET.txt
  VITE_FIREBASE_SENDER_ID:
    file: ./secret_VITE_FIREBASE_SENDER_ID.txt
  VITE_FIREBASE_APP_ID:
    file: ./secret_VITE_FIREBASE_APP_ID.txt
  VITE_YELP_API_KEY:
    file: ./sercret_VITE_YELP_API_KEY.txt
  VITE_WEATHER_API_KEY:
    file: ./secret_VITE_WEATHER_API_KEY.txt