services:
  backend:
    build: ./backend
    container_name: dramm_backend
    environment:
      REDIS_HOST: cache
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports: 
      - "127.0.0.1:3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - cache
    


    
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      VITE_FIREBASE_KEY: ${VITE_FIREBASE_KEY}
      VITE_FIREBASE_DOMAIN: ${VITE_FIREBASE_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_SENDER_ID: ${VITE_FIREBASE_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_YELP_API_KEY: ${VITE_YELP_API_KEY}
      VITE_WEATHER_API_KEY: ${VITE_WEATHER_API_KEY}
      PORT: 8000
    stdin_open: true
    ports: 
      # - "127.0.0.1:5173:5173"
      - "8000:80"
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: dramm
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  cache:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server
    #["redis-stack-server", "/etc/redis/redis.conf"] 
    #redis-stack-server --requirepass sOmE_sEcUrE_pAsS
    volumes: 
      - cache:/data
    
  # nginx:
  #   image: nginx:1.16.0-alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #      - backend
  #      - frontend

volumes:
  mongo-data:
    driver: local
  cache:
    driver: local


# secrets:
#   VITE_FIREBASE_KEY: 
#     #file: secret_VITE_FIREBASE_KEY.txt
#     environment: VITE_FIREBASE_KEY
#   VITE_FIREBASE_DOMAIN:
#     #file: secret_VITE_FIREBASE_DOMAIN.txt
#     environment: VITE_FIREBASE_DOMAIN
#   VITE_FIREBASE_PROJECT_ID:
#    # file: secret_VITE_FIREBASE_PROJECT_ID.txt

#     environment: VITE_FIREBASE_PROJECT_ID
#   VITE_FIREBASE_STORAGE_BUCKET:
#     #file: secret_VITE_FIREBASE_STORAGE_BUCKET.txt
#     environment: VITE_FIREBASE_STORAGE_BUCKET
#   VITE_FIREBASE_SENDER_ID:
#     #file: secret_VITE_FIREBASE_SENDER_ID.txt
#     environment: VITE_FIREBASE_SENDER_ID
#   VITE_FIREBASE_APP_ID:
#     #file: secret_VITE_FIREBASE_APP_ID.txt
#     environment: VITE_FIREBASE_APP_ID
#   VITE_YELP_API_KEY:
#     #file: secret_VITE_YELP_API_KEY.txt
#     environment: VITE_YELP_API_KEY
#   VITE_WEATHER_API_KEY:
#     #file: secret_VITE_WEATHER_API_KEY.txt
#     environment: VITE_WEATHER_API_KEY
#   MONGO_INITDB_ROOT_PASSWORD:
#     #file: secret_MONGO_INITDB_ROOT_PASSWORD.txt
#     environment: MONGO_INITDB_ROOT_PASSWORD
# #   # REDIS_PASSWORD:
# #   #   environment: REDIS_PASSWORD
