
name: CI/CD

on:
  push:
    branches: [main, master, cd-docker, jr-docker]  
  workflow_dispatch: 

env:
# The hostname used to communicate with the Redis service container
  REDIS_HOST: redis
# The default Redis port
  REDIS_PORT: 6379
  MONGODB_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_INITDB_ROOT_PASSWORD }}
  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
  VITE_FIREBASE_DOMAIN: ${{ secrets.VITE_FIREBASE_DOMAIN }}
  VITE_FIREBASE_KEY: ${{ secrets.VITE_FIREBASE_KEY }}

  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}

  VITE_FIREBASE_SENDER_ID: ${{ secrets.VITE_FIREBASE_SENDER_ID }}


  VITE_YELP_API_KEY: ${{ secrets.VITE_YELP_API_KEY }}

  VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 


      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
        env:
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_INITDB_ROOT_PASSWORD }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_DOMAIN: ${{ secrets.VITE_FIREBASE_DOMAIN }}
          VITE_FIREBASE_KEY: ${{ secrets.VITE_FIREBASE_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_SENDER_ID: ${{ secrets.VITE_FIREBASE_SENDER_ID }}
          VITE_YELP_API_KEY: ${{ secrets.VITE_YELP_API_KEY }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}


      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        env: 
            MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_INITDB_ROOT_PASSWORD }}
        with:
          context: ./backend
          file: ./backend/Dockerfile
          
          build-args: |
            MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_INITDB_ROOT_PASSWORD }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dramm-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args:  |
            VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
            VITE_FIREBASE_DOMAIN=${{ secrets.VITE_FIREBASE_DOMAIN }}
            VITE_FIREBASE_KEY=${{ secrets.VITE_FIREBASE_KEY }}
            VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
            VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
            VITE_FIREBASE_SENDER_ID=${{ secrets.VITE_FIREBASE_SENDER_ID }}
            VITE_YELP_API_KEY=${{ secrets.VITE_YELP_API_KEY }}
            VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }}
            VITE_API_URL=dramm-backend:3001
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dramm-frontend:latest
